More changes to installation script, now with system and home directory installation methods

diff --git a/install_zsh b/install_zsh
--- a/install_zsh
+++ b/install_zsh
@@ -1,54 +1,74 @@
 #!/bin/bash
-echo "Checking if zsh is installed...."
-if ! [ -x "$(command -v zsh)" ]; then
-        echo ' - Error: zsh is not installed.' >&2
-        exit 1
-else
-        ZSH_SHELL=`which zsh`
-        echo "- ZSH is installed in $ZSH_SHELL"
-fi
 
-echo "Checking if zsh is the default shell"
-if ! [ $SHELL == *"zsh" ]; then
-        echo "- Your default shell isn't zsh, use chsh to change it to zsh."
-fi
-
-echo "Checking if git is installed...."
-if ! [ -x "$(command -v git)" ]; then
-        echo ' - You need to install git!'
-        exit 1
-else
-        echo " - GIT is installed!"
-fi
-
-echo "\n---\n---\n\n"
-exit 1
+# Functions
+install_method() {
+	echo "Do you want to install system wide or home only? (s/h)"
+	read INSTALL
+}
 
 clone_repository() { 
-	echo "- Start Cloning repository into $1..."
+	echo -e "- Start Cloning repository into $1..."
 	# wget https://raw.githubusercontent.com/jordantrizz/zsh/master/install
 	git clone --recursive https://github.com/jordantrizz/zsh.git $1
 }
 
 
 setup_home() {
-	echo "Setting up home based .zshrc..."
-	if ! [ -f "$HOME/.zshrc" ]; then
+	if ! [ -f $HOME."/.zshrc" ]; then
 	       	ln -s $HOME/zsh/.zshrc ~/.
-	       	echo "- ZSH in-place, type zsh to start your shell"
+	       	clone_repository "$HOME/zsh"
+	       	echo -e " - ZSH in-place, type zsh to start your shell\n"
 	else
-	       	echo "- There's already a .zshrc in-place, remove it and re-run"
+	       	echo -e " - There's already a .zshrc in-place, remove it and re-run\n"
 	       	exit 1
 	fi
 }
 
 setup_system() {
-	echo "Setting up system based .zshrc..."
+	echo -e "Setting up system based .zshrc..."
+	SYSTEM=/usr/local/sbin
 	if ! [ -d "$SYSTEM/zsh" ]; then
-		echo " - Cloning into $SYSTEM/zsh"
-		clone_repository("$SYSTEM/zsh")
+		echo -e " - Cloning into $SYSTEM/zsh\n"
+		clone_repository "$SYSTEM/zsh"
 	else
-		echo " - $SYSTEM/zsh already exists"
+		echo -e " - $SYSTEM/zsh already exists\n"
 		exit 1
 	fi
 }		
+
+# Main
+echo "Checking if zsh is installed...."
+if ! [ -x "$(command -v zsh)" ]; then
+        echo -e " - Error: zsh is not installed.\n"
+        exit 1
+else
+        ZSH_SHELL=`which zsh`
+        echo -e " - ZSH is installed in $ZSH_SHELL\n"
+fi
+
+echo -e "Checking if zsh is the default shell"
+if ! [[ $SHELL == *"zsh" ]]; then
+        echo -e " - Your default shell isn't zsh, use chsh to change it to zsh.\n"
+else
+        echo -e " - ZSH is your default shell!\n"
+fi
+
+echo "Checking if git is installed...."
+if ! [ -x "$(command -v git)" ]; then
+        echo -e " - You need to install git!\n"
+        exit 1
+else
+        echo -e " - GIT is installed!\n"
+fi
+
+echo -e "---\n\nBegin Install\n"
+
+install_method
+
+if [ $INSTALL = "s" ]; then
+        setup_system
+elif [ $INSTALL = "h" ]; then
+        setup_home
+else
+        install_method "Choose s or h on your keyboard"
+fi
