Updated install script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -8,31 +8,26 @@
 #--------------------
 
 flight_check() {
-	# Checking what package manager we have
-	echo -n "Checking what package manager we have...."
-	if [ -x "$(command -v apt)" ]; then
-		echo "We have apt!"
-		PKG_MANAGER="apt"
-	elif [ -x "$(command -v yum)" ]; then
-		echo "We have yum!"
-		PKG_MANAGER="yum"
-	fi
-	
         # Checking if zsh is installed
         echo -n "Checking if zsh is installed...."
         if ! [ -x "$(command -v zsh)" ]; then
                 echo -e "- Error: zsh is not installed."
                 echo -e "- Trying to install via $PKG_MANAGER...."
-                if [[ $PKG_MANAGER == "apt" ]]; then 
-                	sudo apt-get install zsh
-                	if [ $? -eq 1 ];then echo "zsh install failed....";exit 1; fi
-                elif [[ $PKG_MANAGER == "yum" ]]; then 
-                	sudo yum install zsh
-			if [ $? -eq 1 ];then echo "zsh install failed....";exit 1; fi
-		fi
+                pkg_install("zsh")
         else
                 ZSH_SHELL=`which zsh`
                 echo -e "- ZSH is installed in $ZSH_SHELL"
+        fi
+        
+        # Checking if git is installed
+        echo -n "Checking if git is installed...."
+        if ! [ -x "$(command -v git)" ]; then
+                echo -e "- Error: zsh is not installed."
+                echo -e "- Trying to install via $PKG_MANAGER...."
+                pkg_install("zsh")
+                exit 1
+        else
+                echo -e "- GIT is installed!"
         fi
 
         # Check if zsh is the default shell
@@ -43,13 +38,18 @@ flight_check() {
                 echo -e "- ZSH is your default shell!"
         fi
 
-        # Checking if git is installed
-        echo -n "Checking if git is installed...."
-        if ! [ -x "$(command -v git)" ]; then
-                echo -e "- You need to install git!"
-                exit 1
-        else
-                echo -e "- GIT is installed!"
+}
+
+pkg_install() {
+        # Checking what package manager we have
+        echo -n "Checking what package manager we have...."
+        if [ -x "$(command -v apt)" ]; then
+                echo "We have apt!"
+                sudo yum install zsh
+                if [ $? -eq 1 ];then echo "$@ install failed....";exit 1;else;echo "$@ installed successfully"; fi
+        elif [ -x "$(command -v yum)" ]; then
+                echo "We have yum!"
+		if [ $? -eq 1 ];then echo "$@ install failed....";exit 1;else;echo "$@ installed successfully"; fi
         fi
 }
 
